<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class NotificationController extends Controller
{
    /**
     * Get all notifications for the authenticated user
     */
    public function index(Request $request)
    {
        // Try to get user from request if Auth facade fails
        $user = $request->user();
        $recipientId = $user ? $user->user_id : Auth::id();
        
        // Fallback for testing/debugging if still null (REMOVE IN PRODUCTION)
        if (!$recipientId && $request->header('X-User-Id')) {
            $recipientId = $request->header('X-User-Id');
        }

        $notifications = DB::table('notifications')
            ->where('recipient_id', $recipientId)
            ->orderBy('created_at', 'desc')
            ->paginate(20);

        return response()->json([
            'success' => true,
            'debug_user_id' => $recipientId, // Debugging line
            'data' => $notifications
        ]);
    }

    /**
     * Mark a notification as read
     */
    public function markAsRead(Request $request, $id)
    {
        // Try to get user from request if Auth facade fails
        $user = $request->user();
        $userId = $user ? $user->user_id : Auth::id();
        
        // Fallback for testing/debugging if still null (REMOVE IN PRODUCTION)
        if (!$userId && $request->header('X-User-Id')) {
            $userId = $request->header('X-User-Id');
        }

        // Handle random IDs generated by frontend fallback
        if (str_contains($id, '.')) {
             // It's a random ID generated by frontend, we can't update DB
             // Just return success to make UI happy
             return response()->json(['success' => true, 'message' => 'Marked as read (virtual)']);
        }

        $updated = DB::table('notifications')
            ->where('notification_id', $id)
            ->where('recipient_id', $userId)
            ->update(['is_read' => 1, 'read_at' => now()]);

        if ($updated) {
            return response()->json(['success' => true, 'message' => 'Marked as read']);
        }

        // Try without recipient check (maybe the notification exists but user mismatch)
        $exists = DB::table('notifications')->where('notification_id', $id)->exists();
        if (!$exists) {
            return response()->json(['success' => false, 'message' => 'Notification not found'], 404);
        }

        // Notification exists but not for this user
        return response()->json(['success' => false, 'message' => 'Unauthorized'], 403);
    }

    /**
     * Mark all notifications as read
     */
    public function markAllAsRead(Request $request)
    {
        // Try to get user from request if Auth facade fails
        $user = $request->user();
        $userId = $user ? $user->user_id : Auth::id();
        
        // Fallback for testing/debugging if still null (REMOVE IN PRODUCTION)
        if (!$userId && $request->header('X-User-Id')) {
            $userId = $request->header('X-User-Id');
        }

        DB::table('notifications')
            ->where('recipient_id', $userId)
            ->update(['is_read' => 1, 'read_at' => now()]);

        return response()->json(['success' => true, 'message' => 'All marked as read']);
    }
    
    /**
     * Get unread count
     */
    public function unreadCount(Request $request)
    {
        // Try to get user from request if Auth facade fails
        $user = $request->user();
        $userId = $user ? $user->user_id : Auth::id();
        
        // Fallback for testing/debugging if still null (REMOVE IN PRODUCTION)
        if (!$userId && $request->header('X-User-Id')) {
            $userId = $request->header('X-User-Id');
        }
        
        $count = DB::table('notifications')
            ->where('recipient_id', $userId)
            ->where('is_read', false)
            ->count();
            
        return response()->json(['success' => true, 'count' => $count]);
    }
}
